GreenUrban/GreenUrban/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webstore.urls')),  
    path('retailer_login/', include('retailer.urls')),
    path('delivery_login/', include('delivery.urls')),
]

GreenUrban/delivery/urls.py
from django.urls import path
from .views import DeliveryBoyLoginView, DeliveryBoyLogoutView, DeliveryDashboardView,order_dispatch, pickup_view, scan_qr_code, order_details, mark_as_out_for_delivery, start_qr_scanner, out_to_deliver, mark_as_delivered, out_for_delivery_orders,user_detail

urlpatterns = [
    path('', DeliveryBoyLoginView.as_view(), name='delivery_boy_login'),
    path('logout/', DeliveryBoyLogoutView.as_view(), name='delivery_boy_logout'),
    path('dashboard/', DeliveryDashboardView.as_view(), name='delivery_dashboard'),
    path('order_dispatch/', order_dispatch, name='order_dispatch'),
    path('out_to_deliver/', order_dispatch, name='out_to_deliver'),
    path('delivered/', order_dispatch, name='delivered'),
    path('pickupview/', pickup_view, name='pickupview'),
    path('user_detail/<int:user_id>/', user_detail, name='user_detail'),
    path('scan_qr_code/', scan_qr_code, name='scan_qr_code'),
    path('start_qr_scanner/', start_qr_scanner, name='start_qr_scanner'),
    path('order_details/<int:order_id>/', order_details, name='order_details'),
    path('mark_as_out_for_delivery/<int:order_id>/', mark_as_out_for_delivery, name='mark_as_out_for_delivery'),
    path('deliver/', out_to_deliver, name='deliver'),
    path('order/<int:order_id>/out_for_delivery/', mark_as_out_for_delivery, name='mark_as_out_for_delivery'),
    path('order/<int:order_id>/delivered/', mark_as_delivered, name='mark_as_delivered'),
    path('out_for_delivery/', out_for_delivery_orders, name='out_for_delivery_orders'),
    path('order/<int:order_id>/delivered/', mark_as_delivered, name='mark_as_delivered'),
]

GreenUrban/webstore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('login_view', views.login_view, name='login_view'),
    path('register_view', views.register_view, name='register_view'),
    path('home', views.home, name='home'),
    path('account', views.account, name='account'),
    path('register_user', views.register_user, name='register_user'),
    path('login_user', views.login_user, name='login_user'),
    path('logout_user', views.logout_user, name='logout_user'),
    path('pic_upload', views.pic_upload, name='pic_upload'),
    path('shopping/', views.product_list, name='shopping'),
    path('scrap/', views.scrap, name='scrap'),
    path('sewage/', views.product_list, name='sewage'),
    path('land/', views.product_list, name='land'),
    path('shop_products', views.shop_products, name='shop_products'),
    path('add_to_favorites/<int:product_id>/', views.add_to_favorites, name='add_to_favorites'),
    path('favorites/', views.view_favorites, name='view_favorites'),
    path('products/<int:id>/', views.view_product, name='view_product'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('buy_now/<int:product_id>/', views.buy_now, name='buy_now'),
    path('profile_upload', views.profile_update, name='profile_upload'),
    path('buy_now/<int:product_id>/', views.buy_now, name='buy_now'),
    path('order_summary/<int:order_id>/', views.order_summary, name='order_summary'),
    path('cancel_order/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('retailer_login/', include('retailer.urls')),
    path('upload-scrap/', views.upload_scrap, name='upload_scrap'),
    path('delivery_login/', include('delivery.urls')), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    

GreenUrban/webstore/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings


class OTP(models.Model):
    email = models.EmailField()
    otp = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)


class RegisteredUser(AbstractUser):
    img = models.ImageField(null=True, blank=True)
    name = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    pincode = models.PositiveIntegerField(blank=True, null=True)
    number = models.CharField(max_length=10, unique=True)
    address = models.TextField()# New field for storing coins, default set to 500

    def __str__(self):
        return self.username


class Scrap(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)  
    category = models.CharField(max_length=100)  
    description = models.CharField(max_length=225)
    img1 = models.ImageField(upload_to='scrap_images/', null=False)
    img2 = models.ImageField(upload_to='scrap_images/', null=False)
    img3 = models.ImageField(upload_to='scrap_images/', null=False)

    def __str__(self):
        return f"Scrap by {self.user.username}"

GreenUrban/webstore/forms.py
from django import forms
from .models import RegisteredUser,Scrap

class ProfilePictureForm(forms.ModelForm):
    class Meta:
        model = RegisteredUser
        fields = ['img']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = RegisteredUser
        fields = ['name', 'email', 'pincode', 'number', 'address', 'img']

class RegistrationForm(forms.Form):
    name = forms.CharField(max_length=255)
    email = forms.EmailField()
    username = forms.CharField(max_length=255)
    pincode = forms.IntegerField()
    number = forms.CharField(max_length=10)
    address = forms.CharField(widget=forms.Textarea)
    password = forms.CharField(widget=forms.PasswordInput)

class LoginForm(forms.Form):
    username = forms.CharField(max_length=255, required=True)
    password = forms.CharField(widget=forms.PasswordInput, required=True)

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        password = cleaned_data.get("password")
        return cleaned_data

class ScrapForm(forms.ModelForm):
    class Meta:
        model = Scrap
        fields = ['category', 'description', 'img1', 'img2', 'img3']

GreenUrban/webstore/views.py
from django.core.mail import send_mail
from django.http import JsonResponse
from django.db import IntegrityError
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .models import RegisteredUser
from retailer.models import Product, ProductImage, ProductReview, Favorite, Order
from .forms import ProfilePictureForm, ProfileUpdateForm, RegistrationForm, LoginForm
from django.core.files.storage import FileSystemStorage
from django.db.models import Count
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .forms import ScrapForm

def index(request):
    return render(request, 'index.html')

def product_list(request):
    products = Product.objects.all()
    return render(request, 'shopping.html', {'products': products})

def view_product(request, id):
    product = get_object_or_404(Product, id=id)
    images = ProductImage.objects.filter(product=product)
    reviews = ProductReview.objects.filter(product=product).order_by('-rating')
    total_images = images.count()
    
    total_reviews = reviews.count()
    ratings_distribution = reviews.values('rating').annotate(count=Count('rating')).order_by('-rating')
    ratings_percentage = {rating['rating']: (rating['count'] / total_reviews) * 100 for rating in ratings_distribution}

    similar_products = Product.objects.filter(category=product.category).exclude(id=product.id).order_by('-rating')[:6]

    return render(request, 'view_product.html', {
        'product': product,
        'images': images,
        'reviews': reviews,
        'total_images': total_images,
        'similar_products': similar_products,
        'ratings_distribution': ratings_percentage
    })
    
def shopping(request):
    return render(request, 'shopping.html')

def about(request):
    return render(request, 'about.html')

def scrap(request):
    return render(request, 'scrap.html')

def login_view(request):
    return render(request, 'login.html')

def register_view(request):
    return render(request, 'register.html')

@login_required
def account(request):
    user = request.user
    orders = Order.objects.filter(user=user).order_by('-order_date')
    return render(request, 'account.html', {'user_data': user, 'orders': orders})

def home(request):
    if request.user.is_authenticated:
        return render(request, 'home.html', {'user_data': request.user})
    else:
        return redirect('login_view')

def pic_upload(request):
    if request.user.is_authenticated:
        user_data = request.user

        if request.method == 'POST':
            form = ProfilePictureForm(request.POST, request.FILES, instance=user_data)
            if form.is_valid():
                form.save()
                messages.success(request, 'Image uploaded successfully.')
                return redirect('home')
            else:
                messages.error(request, 'Image upload failed. Please check the form.')

        return render(request, 'home.html', {'user_data': user_data})
    else:
        return redirect('login_view')
    
def profile_update(request):
    if request.user.is_authenticated:
        user_data = request.user

        if request.method == 'POST':
            form = ProfileUpdateForm(request.POST, request.FILES, instance=user_data)
            if form.is_valid():
                form.save()
                messages.success(request, 'Profile updated successfully.')
                return redirect('account')

        form = ProfileUpdateForm(instance=user_data)
        return render(request, 'account.html', {'form': form, 'user_data': user_data})
    else:
        return redirect('login_view')

def register_user(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            registration_data = form.cleaned_data
            registered_user = RegisteredUser(
                name=registration_data['name'],
                email=registration_data['email'],
                username=registration_data['username'],
                pincode=registration_data['pincode'],
                number=registration_data['number'],
                address=registration_data['address'],
            )
            registered_user.set_password(registration_data['password'])
            registered_user.save()
            messages.success(request, 'User registered successfully. Please login!')
            return redirect('login_view')
    else:
        form = RegistrationForm()

    return render(request, 'register.html', {'form': form})

def login_user(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'Login successful.')
                return redirect('home')
            else:
                messages.error(request, 'Invalid username or password.')

    else:
        form = LoginForm()

    return render(request, 'login.html', {'form': form})

def logout_user(request):
    logout(request)
    messages.success(request, 'Logout successful.')
    return redirect('index')

def shop_products(request):
    query = request.GET.get('q', '')
    products = Product.objects.all()
    
    if query:
        products = products.filter(
            Q(name__icontains=query) | 
            Q(description__icontains=query) | 
            Q(category__name__icontains=query) | 
            Q(price__icontains=query) | 
            Q(available__icontains=query)
        )

    return render(request, 'shop.html', {'products': products})

def add_to_favorites(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    Favorite.objects.get_or_create(user=request.user, product=product)
    return redirect(request,'view_product', id=product_id)

def view_favorites(request):
    favorites = Favorite.objects.filter(user=request.user)
    return render(request, 'view_favorites.html', {'favorites': favorites})

def add_to_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    quantity = int(request.POST.get('quantity', 1))
    
    if product.stock >= quantity:
        order = Order.objects.create(
            user=request.user,
            product=product,
            quantity=quantity,
            total_price=product.price * quantity,
            shipping_address=request.user.address,
        )
        product.stock -= quantity
        product.save()
        return redirect('cart')
    else:
        return redirect('product_detail', product_id=product_id)

@login_required
def buy_now(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    quantity = int(request.POST.get('quantity', 1))
    
    if product.stock >= quantity:
        order = Order.objects.create(
            user=request.user,
            product=product,
            quantity=quantity,
            total_price=product.price * quantity,
            shipping_address=request.user.address,
            status=1,
            delivery_boy_id=None,
        )
        product.stock -= quantity
        product.save()
        return redirect('order_summary', order_id=order.id)
    else:
        return redirect('product_detail', product_id=product_id)
    
@login_required
def order_summary(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    user = order.user
    return render(request, 'order_summary.html', {'order': order, 'user': user})

@login_required
def cancel_order(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    if order.status not in [5, 4]: 
        order.status = 0  
        order.save()
    return redirect('order_summary', order_id=order_id)

def upload_scrap(request):
    if request.method == "POST":
        form = ScrapForm(request.POST, request.FILES)
        if form.is_valid():
            scrap = form.save(commit=False)
            scrap.user = request.user
            scrap.save()
            messages.success(request, 'Scrap uploaded successfully! Our pickup team will contact you when the pickup is scheduled.')
            return redirect('home')
        else:
            print(form.errors)
    else:
        form = ScrapForm()

    return render(request, 'scrap.html', {'form': form})

GreenUrban/webstore/templates/account.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>GreenUrban - Account</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'homeassets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'homecss/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="#page-top">{{ user_data.email }}</a>
                <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'home' %}">Home</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'account' %}">Account</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'logout_user' %}">LogOut</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Account Section-->
        <header class="masthead bg-primary text-white text-center">
            <div class="container d-flex align-items-center flex-column">
                <!-- Masthead Avatar Image-->
                {% if user_data.img %}
                <img src="{{ user_data.img.url }}" alt="Profile Picture" style="border-radius: 50%; width: 150px; height: 150px; object-fit: cover;">
                {% else %}
                <h1 class="masthead-heading text-uppercase mb-0">My account, {{ request.session.username }}</h1>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                {% endif %}
                <h2 class="masthead-subheading mb-0">Account Balance: <i class="fas fa-coins"></i> 500 Coins</h2>
            </div>
        </header>
        <section class="page-section bg-light" id="account">
            <div class="container">
                <div class="row">
                    <!-- Account Information Section -->
                    <div class="col-lg-4">
                        <h2 class="text-uppercase">Account</h2>
                        <form method="post" action="{% url 'profile_upload' %}" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="id_name" class="form-label">Name</label>
                                <input type="text" name="name" class="form-control" value="{{ user_data.name }}">
                            </div>
                            <div class="mb-3">
                                <label for="id_email" class="form-label">Email</label>
                                <input type="email" name="email" class="form-control" value="{{ user_data.email }}">
                            </div>
                            <div class="mb-3">
                                <label for="id_pincode" class="form-label">Pincode</label>
                                <input type="text" name="pincode" class="form-control" value="{{ user_data.pincode }}" pattern="[0-9]{6}" title="Please enter a six-digit pincode." required>
                            </div>
                            <div class="mb-3">
                                <label for="id_number" class="form-label">Number</label>
                                <input type="text" name="number" class="form-control" value="{{ user_data.number }}" pattern="[0-9]{10}" title="Please enter a ten-digit Indian phone number." required>
                            </div>
                            <div class="mb-3">
                                <label for="id_address" class="form-label">Address</label>
                                <textarea name="address" class="form-control">{{ user_data.address }}</textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">Update</button>
                        </form>
                        
                        
                        
                    </div>
                    <!-- Orders Section -->
                    <div class="col-lg-4">
                        <h2 class="text-uppercase">Orders</h2>
                        {% for order in orders %}
                        <div class="card mb-4">
                            <div class="card-body">
                                <h4 class="card-title">{{ order.product.name }}</h4>
                                <p class="card-text">Ordered on: {{ order.date_ordered }}</p>
                                <p class="card-text">Status: {{ order.status }}</p>
                                <a href="{% url 'order_summary' order.id %}" class="btn btn-primary">View Order</a>
                            </div>
                        </div>
                        {% endfor %}
                        <a href="{% url 'orders' %}" class="btn btn-secondary">View All Orders</a>
                    </div>
                    <!-- Favourites Section -->
                    <div class="col-lg-4">
                        <h2 class="text-uppercase">Favourites</h2>
                        <div class="list-group">
                            <a href="#" class="list-group-item list-group-item-action">Favourite Item 1</a>
                            <a href="#" class="list-group-item list-group-item-action">Favourite Item 2</a>
                            <a href="#" class="list-group-item list-group-item-action">Favourite Item 3</a>
                        </div>
                        {% comment %} <a href="{% url 'favourites' %}" class="btn btn-secondary mt-4">View All Favourites</a> {% endcomment %}
                    </div>
                </div>
            </div>
        </section>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'homejs/scripts.js' %}"></script>
        <!-- SB Forms JS-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

GreenUrban/webstore/templates/header.html
{% load static%}
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>GreenUrban</title>

  <!-- slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
  <!-- fonts awesome style -->
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />
  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:400,600,700&display=swap" rel="stylesheet" />
  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />
  {% load compress %}
    {% compress css %}
    <link rel="stylesheet" type="text/x-scss" href="{% static 'scss/style.scss' %}">
    {% endcompress %}
</head>

<body>
  <div class="hero_area">
    <!-- header section starts -->
    <header class="header_section">
      <nav class="navbar navbar-expand-lg custom_nav-container">
        <div class="custom_menu-btn">
          <button onclick="openNav()">
            <span class="s-1"> </span>
            <span class="s-2"> </span>
            <span class="s-3"> </span>
          </button>
        </div>
        <div id="myNav" class="overlay">
          <div class="menu_btn-style ">
            <button onclick="closeNav()">
              <span class="s-1"> </span>
              <span class="s-2"> </span>
              <span class="s-3"> </span>
            </button>
          </div>
          <div class="overlay-content">
            <a class="active" href="{% url 'index' %}">
              Home
            </a>
              <a class="" href="{% url 'login_view' %}">
                Login
              </a>
              <a class="" href="{% url 'register_view' %}">
                Register
              </a>
            
           
          </div>
        </div>
        <a class="navbar-brand mx-auto" href="{% url 'index' %}"> <!-- mx-auto class added for centering -->
          <span>
            GreenUrban
          </span>
        </a>
        
      </nav>
    </header>
    <!-- end header section -->
{%block content%}{%endblock%}

GreenUrban/webstore/templates/otp_verification.html
{% extends 'header.html' %}
{% block content %}
<div class="container">
    <h1>OTP Verification</h1>
    <p>An OTP has been sent to {{ email }}. Please enter it below to complete your registration.</p>
    <form method="POST" action="{% url 'verify_otp' %}">
        {% csrf_token %}
        <input type="hidden" name="email" value="{{ email }}">
        <div class="form-group">
            <label for="otp">OTP</label>
            <input type="text" class="form-control" id="otp" name="otp" placeholder="Enter OTP">
        </div>
        <button type="submit" class="btn btn-primary">Verify OTP</button>
    </form>
</div>
{% endblock %}

GreenUrban/webstore/templates/retailer_dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Retailer Dashboard</title>
        <link href="{% static 'homecss/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <h2 class="text-center mt-5">Welcome, {{ retailer.company_name }}</h2>
                    <div class="card mt-4">
                        <div class="card-body">
                            <h5 class="card-title">Company Information</h5>
                            <p class="card-text"><strong>Phone Number:</strong> {{ retailer.phone_number }}</p>
                            <p class="card-text"><strong>Address:</strong> {{ retailer.address }}</p>
                            <p class="card-text"><strong>Registration Date:</strong> {{ retailer.registration_date }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

GreenUrban/webstore/templates/retailer_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Retailer Login</title>
        <link href="{% static 'homecss/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <h2 class="text-center mt-5">Retailer Login</h2>
                    <form method="post" action="{% url 'retailer_login' %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary btn-block">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </body>
</html>